Django_Blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('', include('blog.urls',namespace='blog')),
    path('accounts/',include('accounts.urls',namespace='accounts'))
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.auth import login, logout


app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUpView.as_view(),name='signup'),
]

blog/urls.py
from django.urls import path, include
from . import views
app_name = 'blog'

urlpatterns = [
    path('',views.IndexPage.as_view(),name='index'),
    path('post_create',views.PostCreateView.as_view(),name='post_create'),
    path('post_list',views.PostListView.as_view(),name='post_list'),
    path('post/<int:pk>',views.post_detail,name='post_detail'),
    path('post/<int:pk>/edit/',views.PostUpdateView.as_view(),name='post_edit'),
    path('post/<int:pk>/delete/',views.PostDeleteView.as_view(),name='post_remove'),
    path('analysis/<int:pk>/',views.AnalysisDetailView.as_view(),name='analysis_detail')
]

accounts/models.py
from django.db import models
from django.contrib import auth
from django.utils import timezone


class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return self.username

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import  reverse, reverse_lazy
from django.contrib.auth import get_user_model


# Create your models here.
User = get_user_model()
class Post(models.Model):
    author          = models.ForeignKey(User,on_delete=models.CASCADE)
    title           = models.CharField(max_length=200)
    content         = models.TextField(max_length=3000)
    created_date    = models.DateTimeField(auto_now_add=True)
    edited_date     = models.DateTimeField(blank=True, null=True)
    post_views      = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def viewed(self):
        self.post_views +=1
        self.save() 

    def get_absolute_url(self):
        return reverse('blog:post_detail',kwargs={'pk':self.pk})


class Comment(models.Model):
    post            = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author          = models.CharField(max_length=200)
    content         = models.TextField(max_length=500)
    created_date    = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author} : {self.content}'

    def get_absolute_url(self):
        return reverse('blog:post_detail',kwargs={'pk':self.pk})

book/models.py
from datetime import datetime
from django.db import models

# Create your models here.
# app/models.py

class Author(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField('Book name', max_length=100)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, blank=True, null=True)
    author_email = models.EmailField('Author email', max_length=75, blank=True)
    imported = models.BooleanField(default=False)
    published = models.DateField('Published',default=datetime.now, blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    categories = models.ManyToManyField(Category, blank=True)

    def __str__(self):
        return self.name

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Title'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Content'}))
    class Meta():
        model = Post
        fields = ('title','content')
        
class CommentForm(forms.ModelForm):

    content = forms.CharField(label='Say Something',widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Content'}))
    class Meta():
        model = Comment
        fields =('content',)

accounts/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse,reverse_lazy
from . import forms, models
from django.contrib.auth import get_user_model
class SignUpView(generic.CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("accounts:login")
    template_name = "accounts/signup.html"

blog/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.http import  HttpResponse, JsonResponse, HttpResponseRedirect
from django.utils import timezone
from django.views.generic.edit import FormMixin
from django.template.loader import render_to_string
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.urls import reverse_lazy,reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import (TemplateView, ListView,
                                    DetailView, CreateView,
                                    UpdateView, DeleteView,
                                    )
class IndexPage(TemplateView):
    template_name = 'blog/index.html'

class PostCreateView(LoginRequiredMixin,CreateView):
    login_url = 'accounts/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post
    template_name = 'blog/post_form.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author =self.request.user
        post.save()
        return redirect('blog:post_detail',pk=post.pk)

class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'

class AnalysisDetailView(DeleteView):
    model = Post
    template_name = 'blog/analysis_detail.html'


def analysis_detail(request,pk):
    post = get_object_or_404(Post,pk=pk)
    context ={
        'post':post,
    }
    if request.is_ajax():
        html = render_to_string('blog/pie_chart.html', context=context, request=request)
        return JsonResponse({'form':html})
    return render(request,'blog/analysis_detail.html',context)


def post_detail(request,pk):
    post = get_object_or_404(Post,pk=pk)
    comments = Comment.objects.filter(post=post).order_by('-id')
    if request.method =='GET':
        post.viewed()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            # return redirect('blog:post_detail',pk=post.pk)
    else:
        form = CommentForm()
    context ={
        'post':post,
        'comments':comments,
        'form':form
    }
    if request.is_ajax():
        html = render_to_string('blog/comments.html', context=context, request=request)
        return JsonResponse({'form':html})
    return render(request,'blog/post_detail.html',context)


class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = 'accounts/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin,DeleteView):
    login_url = 'accounts/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post
    success_url = reverse_lazy("blog:post_list")

book/views.py
from django.shortcuts import render

# Create your views here.

templates/accounts/login.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container">
  <h2>Please Login:</h2>

  {% if forms.errors %}
  <p>Username and password didn't match, please try again</p>
  {% endif %}

  <form class="container" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
     {{ form.as_p }}
     <input type="submit" class="btn btn-primary" value="Login">
     <input type="hidden" name="next" value="{{ next }}">
  </form>
</div>
{% endblock %}

templates/accounts/signup.html
{% extends "blog/base.html" %}
{% block content %}

<form method="post">
    {% csrf_token %}
   <h1>Please Sign Up</h1>
   {{form.as_p}}
     <button type="submit" class="btn btn-primary">Sign Up</button>



{% endblock content %}

templates/base_site.html
{% extends "admin/base.html" %}
{% load static %}

{# Additional <head> content here, some extra meta tags or favicon #}
{#{% block extrahead %}#}
{#{% endblock %}#}


{# Additional CSS includes #}
{#{% block extrastyle %}#}
{#  <link rel="stylesheet" type="text/css" href="{% static 'css/my_project.css' %}" media="all">#}
{#{% endblock %}#}


{# Additional JS files in footer, right before </body> #}
{#{% block extrajs %}#}
{#  <script type="text/javascript" src="{% static 'js/my_project.js' %}"></script>#}
{#{% endblock %}#}


{# Footer links (left side) #}
{#{% block footer_links %}#}
{#  <a href="/docs/" class="icon"><i class="icon-question-sign"></i>Documentation</a>#}
{#{% endblock %}#}

{# Additional header content like notifications or language switcher #}
{#{% block header_content %}#}
{#    {{ block.super }}#}
{#    <div class="header-content">#}
{#        <!-- First icon column -->#}
{#        <div class="header-column icon">#}
{#            <i class="icon-home"></i><br>#}
{#            <i class="icon-cog"></i>#}
{#        </div>#}
{#        <div class="header-column" style="margin-right: 20px">#}
{#            <a href="/" class="grey">Front-end</a><br>#}
{#            <a href="" class="grey">One more link</a>#}
{#        </div>#}
{#        <!-- Second icon column -->#}
{#        <div class="header-column icon">#}
{#            <i class="icon-comment"></i>#}
{#        </div>#}
{#        <div class="header-column">#}
{#            <a href="" class="grey">5 new messages</a>#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}

{# Footer branding name (center) #}
{#{% block footer_branding %}#}
{#{% endblock %}#}


{# Footer copyright (right side) #}
{#{% block copyright %}#}
{#  Copyright &copy; 2013 Client<br>Developed by <a href="http://yoursite.com" target="_blank">YourName</a> #}
{#{% endblock %}#}

templates/blog/analysis_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="contianer">
  <h1>{{post.title}}</h1>
  <p> Total Viewd: <span id='post-viewd'> {{post.post_views}} </span></p>
  <p> Comments: <span id='comments'> {{post.comments.all.count}} </span></p>
{% include "blog/pie_chart.html" %}

{% endblock %}

templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Blog</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- Custom Css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- Some Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Russo+One&display=swap" rel="stylesheet">
  </head>
  <body class="loader">
    <!-- NAVBAR -->

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
  <a class="navbar-brand" href="#">Django Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  {% url 'blog:index' as home_url %}
  {% url 'blog:post_list' as post_list_url %}
  {% url 'blog:post_create' as post_create_url %}
  {% url 'accounts:login' as login_url %}
  {% url 'accounts:signup' as signup_url %}

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}
        active
      {% endif %}">
        <a class="nav-link" href="{% url 'blog:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == post_list_url %}
        active
      {% endif %}">
        <a class="nav-link" href="{% url 'blog:post_list' %}">Posts</a>
      </li>
      <li class="nav-item {% if request.path == post_create_url %}
        active
      {% endif %}">
        <a class="nav-link" href="{% url 'blog:post_create' %}">Make a Post</a>
      </li>


      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item {% if request.path == login_url %}
        active
      {% endif %}">
        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
      </li>
      <li class="nav-item {% if request.path == signup_url %}
        active
      {% endif %}">
        <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
      </li>
      {% endif %}

      {% if user.is_authenticated and request.user.is_superuser%}
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
      {% endif %}
    </ul>

  </div>
  </div>
</nav>
    <!-- CONTENT BLOCK -->
    <div class="conetent container">
      <div class="row">
        <div class="col-md-8">
          <div class="blog_posts">
            {% block content %}
            {% endblock %}
          </div>

        </div>

      </div>
    </div>
    <!--Jquery-->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <!--D3..s-->
    <script src="https://d3js.org/d3.v6.js"></script>
    <!--AJAX Comments-->
    <script type="text/javascript" src="{% static 'js/main.js' %}" ></script>
  </body>
</html>

templates/blog/comments.html
<div class="container-fluid mt-2">
  <div class="form-group-row">
    <form class="comment-form" action="{% url 'blog:post_detail' pk=post.pk %}" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class=" btn btn-primary btn-sm" id='update'>Reply</button>
    </form>
  </div>
</div>

<br>
<h5>Comments (<span id='comment'>{{post.comments.all.count}}</span>) :</h5>

{% for comment in post.comments.all %}
<div class="container mt-5" >
  <h6> {{comment.author}} said at {{comment.created_date}} : </h6>
  <h6> {{comment.content}}  </h6>
</div>

{% endfor %}

templates/blog/index.html
{% extends 'blog/base.html' %}
{% block content %}

<h1>Austin Blog</h1>

{% endblock content %}

templates/blog/pie_chart.html
    <script src="https://d3js.org/d3.v6.js"></script>
    <!--pie container-->
    <div id="chart"></div>
    <script>
        /*------set value here-----*/
        var post = {{post.post_views}};
        console.log(typeof(post));
        var comment = {
            name: "留言",
            value: {{post.comments.all.count}}
        };
        var uncomment = {
            name: "僅觀看未留言 ",
            value: post-comment.value
        };
        /*------set value here-----*/
        //change data to pie
        var dataset = [comment,uncomment];
        var pie = d3.pie()
                    .value(d => d.value);
        console.log(pie(dataset));


        var width = 250, height = 250;

        //set the pie radius
        var arc = d3.arc()
                .innerRadius(0)
                .outerRadius(width / 2 - 1);

        //set the text in pie radius
        var arcLabel = d3.arc().innerRadius(width / 2 * 0.5).outerRadius(width / 2 * 0.8);

        //set color
        var color = d3.scaleOrdinal()
                        .domain(dataset.map(d => d.name))
                        .range(d3.quantize(t => d3.interpolateSpectral(t * 0.8 + 0.1), dataset.length).reverse());

        //set svg
        const svg = d3.select('#chart')
                    .append('svg')
                    .attr("viewBox", [-width / 2, -height / 2, width * 2 , height * 2]);

        var g = svg.selectAll(".arc")
                    .data(pie(dataset))
                    .enter().append("g")
                    .attr("class", "arc");

        //draw pie and set color
        g.append("path")
            .attr("d", arc)
            .style("fill", function(d) {
                return color(d.data.value);
            });

        //set the data value as text with some font attribute
        g.append("text")
            .attr("transform", d => `translate(${arcLabel.centroid(d)})`)
            .call(text => text.append("tspan")
                .attr("x", "-0.3em")
                .attr("y", "0.2em")
                .attr("font-size", "0.8em")
                .attr("font-weight", "bold")
                .text(d => d.data.value))
        //set the data name as text with some font attribute
            .call(text => text.append("tspan")
                .attr("x", "-1.3em")
                .attr("y", "-1.3em")
                .attr("font-size", "0.7em")
                .attr("fill-opacity", 0.7)
                .text(d => d.data.name));

    </script>

templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
 <form method="post">
   {% csrf_token %}
   <p>Are you sure you want to delete {{ object }}?</p>
   <input type="submit" class="btn btn-danger btn-sm" name="" value="Confirm">
 </form>
{% endblock %}

templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="contianer">
  <h1>{{post.title}}   <a class=" btn btn-info btn-sm" href="{% url 'blog:analysis_detail' pk=post.pk %}">Analysis</a> </h1>
  <p>author : {{post.author}} </p>
  <p>{{post.created_date}} ,<span id='post'>{{post.post_views}}</span> viewd </p>

<h5 class="postcontent">{{post.content|safe|linebreaksbr}}</h5>
</div>

<h5></h5>

{% if user == post.author %}
<a class="btn btn-primary btn-sm" href="{% url 'blog:post_edit' pk=post.pk %}">Edit</a>
<a class="btn btn-danger btn-sm" href="{% url 'blog:post_remove' pk=post.pk %}">Delete</a>
{% endif %}




<hr>

<div class="main-comment-section">
  {% include 'blog/comments.html' with post=post form=form %}
</div>

{% endblock %}

templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block content %}


<form class="post_form" method="post">
  {% csrf_token %}
  {{form.as_p}}
    <button type="submit" class="save btn btn-default">Post</button>
</form>

{% endblock %}

templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block content %}
<h2 class="mt-3">Posts List:</h2>
{% for post in post_list %}
<div class="container" >
  <div class="card mt-3" style="width: 50rem;">
    <div class="card-body">
      <h4 class="card-title">{{post.title}} </h4>
      <h6>by {{post.author}}</h6>
      <br>
      <p class="card-text">{{post.content|safe|linebreaksbr|truncatechars:30}}</p>
      <a href="{% url 'blog:post_detail' pk=post.pk %}" class="card-link">View</a>
    </div>
  </div>
</div>
{% endfor %}

{% endblock content %}